node:
    client: false
    data: true

cluster:
    name: cloud9

http:
    enabled: false

gateway:
    type: local

index:
    number_of_shards: 5
    number_of_replicas: 1
    analysis:
        filter:
            edgeNGram:
                type: edgeNGram
                min_gram: 1
                max_gram: 25
                side: front

        analyzer:
            string_lowercase:
                tokenizer: keyword
                filter: lowercase

            ngrammer:
                type: custom
                tokenizer: whitespace
                filter: [lowercase, edgeNGram]
